<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sasd.MailWorkbench.Domain\Sasd.MailWorkbench.Domain.csproj" />
    <ProjectReference Include="..\Sasd.MailWorkbench.Application\Sasd.MailWorkbench.Application.csproj" />
  </ItemGroup>
</Project>
