<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sasd.MailWorkbench.Notification.Domain\Sasd.MailWorkbench.Notification.Domain.csproj" />
    <ProjectReference Include="..\Sasd.MailWorkbench.Notification.Contracts\Sasd.MailWorkbench.Notification.Contracts.csproj" />
    <ProjectReference Include="..\Sasd.MailWorkbench.Notification.Application\Sasd.MailWorkbench.Notification.Application.csproj" />
  </ItemGroup>
</Project>
